### ISSUE TITLE
Process NAFO landings

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/comlandr#21]
NAFO data pull and filtering is complete.
Now a review of the processing of the data to match the format of the cfdbs data pull is required.

* Tonnage class, Division codes, species codes, gear codes
* skates & hakes

**Comment by slucey** [comment]
Have made the `process_foreign_data` function more generic to match `get_comland_raw_data`.  Still need to review skates and hakes.

**Comment by slucey** [comment]
Foreign data now matches domestic data.  `disaggregateSkatesHakes` can handle both foreign and domestic data.
