### ISSUE TITLE
Filter NAFO downloads by filterByYear

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/comlandr#27]
Right now the `get_foreign_data` function downloads all NAFO data even if `filterByYear` is passed to it.  This should be a straightforward fix.

**Comment by andybeet** [comment]
@slucey Agreed. I will sort that out

**Comment by andybeet** [comment]
All changes made to the `get_foreign_data` file were somehow lost during a merge. In addition the processing of the skates and hakes are no longer applied in the current `get_comland_data` function. Will create a pull request to reinstate all previous changes
