### ISSUE TITLE
output naming convention

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/comlandr#3]
naming convention required for output data (read and write)

**Comment by andybeet** [comment]
Changed all output to RDS format (in place of Rdata)
used in file names:
meatwt or livewt
EPU or stat.area

**Comment by slucey** [comment]
@andybeet what is the difference between .rda and .RData.  From what I found, they are identical.

**Comment by andybeet** [comment]
RDA and RDATA are identical but i think we should use RDS. You can read these files (readRDS) into a variable of any name rather than an RDA which loads into the environment with the variable name embedded in the file

**Comment by slucey** [comment]
Ah...I misread and thought you switched to RDA.  Thanks.
