### ISSUE TITLE
make plotting functions for package

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/comlandr#7]
@slucey Do you have any existing plotting functions for the comlands output?
I think it might be a good idea to incorporate some into the package. 
Can you either point me to where they are on the server, email me, or upload to the R folder in the repo.

**Comment by slucey** [comment]
I do not.  However, I am looking for ways to practice ggplot2 so if you have some ideas I can try and mock something up.

**Comment by andybeet** [comment]
These are the variables in the aggregated data:
YEAR NESPP3    QY GEAR  SIZE  EPU   UTILCD SPPLIVMT SPPVALUE US   

I was thinking mostly of faceted time series plots like (not an exhaustive list) :

* SPPLIVMT/SPPVALUE by functional group (passed as an argument) for each EPU (something like you do for the SOE)
* SPPLIVMT/SPPVALUE by GEAR for each EPU
* SPPLIVMT/SPPVALUE by vessel SIZE for each EPU
 
Maybe also add QY in facet grid or make an argument to function, similarly with US/Non.  Something along those lines

Of course the user of the package can always make their own plots but it might be nice to have a few pre-written functions to quickly display some of the data.

**Comment by slucey** [comment]
Plot function is in good shape now.  You can specify any column as a "by" group for the facet grid.  The user can also specify a range of years and whether to plot landings or value.

**Comment by andybeet** [comment]
looks great. nice job
